packages:
  - apps/*
  - packages/*
overrides:
  "@emnapi/core": 2.0.0-alpha.3
  "@emnapi/runtime": 2.0.0-alpha.3
catalog:
  "@types/bun": ^1.3.14
  dotenv: ^17.4.2
  zod: ^4.4.3
allowBuilds:
  "@google/genai": false
  protobufjs: false
